config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  resources :problems do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :problem

  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :problem
  belongs_to :user
  validates_uniqueness_of :problem_id, scope: :user_id
end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  attachment :image

  with_options presence: true do
    validates :title
    validates :body
    validates :image
  end

  def self.search(search)
    if search != ""
      Problem.where('title LIKE(?)', "%#{search}%")
    else
      Problem.all
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"

    belongs_to :following, class_name: "User"

    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
  attachment :profile_image

  has_many :problems, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_problems, through: :likes, source: :problem
  def already_liked?(problem)
    self.likes.exists?(problem_id: problem.id)
  end

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

 #フォローしているかを確認
 def following?(user)
   following_relationships.find_by(following_id: user.id)
 end

 #フォローするとき
 def follow(user)
   following_relationships.create!(following_id: user.id)
 end

 #フォローを外すとき
 def unfollow(user)
   following_relationships.find_by(following_id: user.id).destroy
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    problems_path
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :age])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html {redirect_to problem_path(params[:problem_id]) }
      format.json
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, problem_id: params[:problem_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(problem_id: params[:problem_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(problem_id: params[:problem_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_user!, expect: [:index]

  def index
    @problems = Problem.all.page(params[:page]).per(5).order('created_at DESC')
    @like = Like.new
    @all_ranks = Problem.find(Like.group(:problem_id).order('count(problem_id) desc').limit(3).pluck(:problem_id))
   end

  def show
    @like = Like.new
    @comment = Comment.new
    @comments = @problem.comments.includes(:user)
  end

  def new
    @problem = Problem.new
  end

  def create
    @problem = Problem.new(problem_params)
    @problem.user_id = current_user.id
    if @problem.save
      redirect_to problem_path(@problem), notice: "#{@problem.title}投稿に成功しました"
    else
      render :new
    end
  end

  def edit
    if @problem.user != current_user
      redirect_to problems_path, alert: '不正なアクセスです'
    end
  end

  def update
    if @problem.update(problem_params)
      redirect_to problem_path(@problem), notice:"#{@problem.title} 投稿しました"
    else
      render :edit
    end
  end

  def destroy
    @problem.destroy
    redirect_to problems_path, notice:'に成功しました'
  end

  def search
    @problems = Problem.search(params[:keyword])
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  private
  def set_problem
    @problem = Problem.find(params[:id])
  end

  def problem_params
    params.require(:problem).permit(:title, :body, :image, :classification)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:following_id])
    current_user.follow(@user)
  end

  def destroy
    @user = User.find(params[:id])
    current_user.unfollow(@user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, expect: [:index]
  before_action :gest_test_user, only: [:edit,:update,:destroy]

  def index
    # @users = User.all
    @users = User.all.page(params[:page]).per(6).order('created_at DESC')
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: '不正なアクセスです'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice:'更新に成功しました'
    else
      render :edit
    end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end

  def gest_test_user
    @user = User.find(params[:id])
    if @user.email == "test@example.com"
      flash[:notice] = "テストユーザーのため変更できません"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like.html.erb
  <% if current_user.already_liked?(@problem) %>
    <label>
      <i class="fas fa-heart favorite__heart">
         <%= button_to 'いいねを取り消す', problem_like_path(@problem), method: :delete , class: "favorite", remote: true  %>
      </i>
    </label>
     <span class="favorite__count"><%= @problem.likes.count %></span>
  <% else %>
    <label>
      <i class="far fa-heart favorite__heart">
      <%= button_to '', problem_likes_path(@problem), class: "favorite", remote: true  %>
      </i>
    </label>
     <span class="favorite__count"><%= @problem.likes.count %></span>
  <% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @problem.id %>').html("<%= j(render partial: 'likes/like') %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @problem.id %>').html("<%= j(render partial: 'likes/like') %>");

app/views/problems/edit.html.erb
<section class="new">
  <div class="side-header">
    <div class="side-header__top">
      <%= link_to problems_path, class: "header__top-text"  do %>
        <span class="header__animals">Animals</span>
        <span class="header__domi">Domi</span>
      <% end %>
      <div class="side-header__i">
        <i class="fab fa-themeisle icon"></i>
        <%= link_to "トップへ戻る", problems_path , class: "side-header__btn"%>
      </div>
      <div class="side-header__i">
        <i class="fas fa-cannabis icon"></i>
        <%= link_to "投稿する", new_problem_path, class: "side-header__btn"%>
      </div>
      <div class="side-header__i">
        <i class="fas fa-dog icon"></i>
        <%= link_to "MYページ", user_path(current_user) , class: "side-header__btn "%>
      </div>
      <div class="side-header__i">
        <i class="fas fa-sign-out-alt icon"></i>
        <%= link_to "ログアウト", destroy_user_session_path , data: { confirm: "本当にログアウトします？"},method: :delete, class: "side-header__btn"%>
      </div>
    </div>
  </div>

  <% if @problem.errors.any?%>
    <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @problem.errors.full_messages.each do |message|%>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
 <div class="message">
    <div class="message__container">
      <h1  class="page-title">記事編集</h1>
      <%= form_with model: @problem do |f|%>
        <div class="message__box">
          <div class="field">
            <%= f.label :title, 'タイトル', class: "field__name"%>
            <%= f.text_field :title, class: "field__post"%>
          </div>
          <div class="field">
            <p class="field__select">選択してください</p>
            <div class="radio-box">
              <%= f.radio_button :classification ,"動物関係"%>
              <%= f.label :classification, '動物関係', class: "field__radio-name"%>
              <%= f.radio_button :classification, "環境関係"%>
              <%= f.label :classification, '環境関係', class: "field__radio-name"%>
            </div>
          </div>
          <div class="field">
            <%= f.label :body , '詳細', class: "field__name"%>
            <%= f.text_area :body, class: "field__body"%>
          </div>
          <div class="field">
            <div id="image-preview">
              <%= f.label :image, '写真', class: "field__name"%>
              <%= attachment_image_tag @problem, :image, class: "img-square", fallback: "no_image.jpg", size:"150x150" ,style: "border-radius: 50%"%>
            </div>
              <%= f.attachment_field :image,  id: "preview", class: "field__image-box"%>
          </div>
          <%= f.submit '編集完了', class: "field__btn solid"%>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/problems/index.html.erb
<header class="header">
  <div class="header__top">
    <div class="search">
      <%= form_with(url: search_problems_path, local: true, method: :get, class: "search__form") do |f| %>
        <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search__input" %>
        <%= f.submit "検索", class: "search__btn" %>
      <% end %>
    </div>
    <%= link_to problems_path, class: "header__top-text"  do %>
      <span class="header__animals">Animals</span>
      <span class="header__domi">Domi</span>
    <% end %>
    <%= link_to "投稿する", new_problem_path, class: "header__btn"%>
    <%= link_to 'ユーザー一覧', users_path, class: "header__btn"%>
    <%= link_to "ログアウト", destroy_user_session_path , data: { confirm: "本当にログアウトします？"},method: :delete, class: "header__btn"%>
  </div>
</header>

<div class="post-index">
  <div class="side-mypage">
    <div class="side-mypage__box">
      <h3 class="side-mypage__name"><%= current_user.username%></h3>
      <%= attachment_image_tag current_user, :profile_image, fallback: "no-image.png",class: "side-mypage__img"%>
      <p><%= link_to "MYページ", user_path(current_user) , class: "side-mypage__my"%></p>
     </div>
  </div>
  <h1 class="post-index__top-title">Ranking</h1>
  <% @all_ranks.each.with_index(1) do |post, i| %>
    <div class="post-index__card-box">
      <div class="rank"><%= i%></div>
      <div class="post-index__user-inner">
        <%= link_to user_path(post.user.id) do %>
          <%= attachment_image_tag post.user, :profile_image, fallback: "no-image.png", size: "72x72", style: "border-radius: 50%;"%>
          <p><%= link_to post.user.username, user_path(post.user.id),  class: "post-index__username"%></p>
        <% end %>
      </div>
      <%= link_to problem_path(post) do %>
        <div class="post-index__info">
          <div class="post-index__info-post">
            <%= link_to problem_path(post), class: "post-index__index-image" do %>
              <%= attachment_image_tag post, :image, size: "75x75", style: "border-radius: 10%;" %>
            <% end %>
          </div>
          <div class="post-index__right">
            <h4 class="post-index__classification"><%= post.classification%></h4>
            <%= link_to problem_path(post), class: "post-index__user-title" do %>
              <h2 class="post-index__title"><%= post.title%></h2>
              <%= truncate(post.body, length: 100) do %>
                <p><%= link_to "続きを読む・・",problem_path(post), class: "post-index__truncate"%><p>
              <% end %>
            <% end %>
            <div class="favorite-box">
              <i class="fas fa-heart favorite__heart"></i>
              <%= post.liked_users.count %>人がいいねしてます
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="post-index">
  <div class="post-index__sharp">
    <h1 class="post-index__top-title">News List</h1>
  </div>
  <div class="post-index__container">
    <% @problems.each do |problem|%>
      <div class="post-index__card-box">
        <div class="post-index__user-inner">
          <%= link_to user_path(problem.user.id) do %>
            <%= attachment_image_tag problem.user, :profile_image, fallback: "no-image.png", size: "72x72", style: "border-radius: 50%;"%>
            <p><%= link_to problem.user.username, user_path(problem.user.id),  class: "post-index__username"%></p>
          <% end %>
        </div>
        <div class="post-index__info">
          <div class="post-index__info-post">
            <%= link_to problem_path(problem), class: "post-index__index-image" do %>
              <%= attachment_image_tag problem, :image, size: "75x75", style: "border-radius: 10%;" %>
            <% end %>
          </div>
          <div class="post-index__right">
            <%= link_to problem_path(problem), class: "post-index__user-title" do %>
              <h4 class="post-index__classification"><%= problem.classification%></h4>
              <h2 class="post-index__title"><%= problem.title%></h2>
              <%= truncate(problem.body, length: 100) do %>
                <p><%= link_to "続きを読む・・",problem_path(problem), class: "post-index__truncate"%><p>
              <% end %>
            <% end %>
            <div class="favorite-box">
              <i class="fas fa-heart favorite__heart"></i>
              <%= problem.liked_users.count %>人がいいねしてます
            </div>
              <p class="date">作成日: <%= problem.updated_at.strftime("%Y-%m-%d %H:%M")%></p>
          </div>
        </div>
      </div>
    <%end %>
    <div class="paginate"><%= paginate @problems %></div>
  </div>
</div>

app/views/problems/search.html.erb
<header class="header">
  <div class="header__top">
    <div class="search">
      <%= form_with(url: search_problems_path, local: true, method: :get, class: "search__form") do |f| %>
        <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search__input" %>
        <%= f.submit "検索", class: "search__btn" %>
      <% end %>
    </div>
    <%= link_to problems_path, class: "header__top-text"  do %>
      <span class="header__animals">Animals</span>
      <span class="header__domi">Domi</span>
    <% end %>
    <%= link_to "投稿する", new_problem_path, class: "header__btn"%>
    <%= link_to "MYページ", user_path(current_user) , class: "header__btn "%>
    <%= link_to 'ユーザー一覧', users_path, class: "header__btn"%>
    <%= link_to "ログアウト", destroy_user_session_path , data: { confirm: "本当にログアウトします？"},method: :delete, class: "header__btn"%>
  </div>
</header>
<div class="contents-row">
  <h1  class="page-title">検索結果</h1>
  <% @problems.each do |problem| %>
    <div class="post-index__card-box">
      <div class="post-index__user-inner">
        <%= link_to user_path(problem.user.id) do %>
          <%= attachment_image_tag problem.user, :profile_image, fallback: "no-image.png", size: "72x72", style: "border-radius: 50%;"%>
          <p><%= link_to problem.user.username, user_path(problem.user.id),  class: "post-index__username"%></p>
        <% end %>
      </div>
      <div class="post-index__info">
        <div class="post-index__info-post">
          <%= link_to problem_path(problem), class: "post-index__index-image" do %>
            <%= attachment_image_tag problem, :image, size: "75x75", style: "border-radius: 10%;" %>
          <% end %>
        </div>
        <div class="post-index__right">
          <%= link_to problem_path(problem), class: "post-index__user-title" do %>
            <h2 class="post-index__title"><%= problem.title%></h2>
            <%= truncate(problem.body, length: 100) do %>
              <p><%= link_to "続きを読む・・",problem_path(problem), class: "post-index__truncate"%><p>
            <% end %>
          <% end %>
          <div class="favorite-box">
            <i class="fas fa-heart favorite__heart"></i>
            <%= problem.liked_users.count %>
          </div>
            <p class="date">作成日: <%= problem.updated_at.strftime("%Y-%m-%d %H:%M")%></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/problems/show.html.erb
<section class="new">
  <div class="side-header">
    <div class="side-header__top">
      <%= link_to problems_path, class: "header__top-text"  do %>
        <span class="header__animals">Animals</span>
        <span class="header__domi">Domi</span>
      <% end %>
      <div class="side-header__i">
        <i class="fab fa-themeisle icon"></i>
        <%= link_to "トップへ戻る", problems_path , class: "side-header__btn"%>
      </div>
      <div class="side-header__i">
        <i class="fas fa-cannabis icon"></i>
        <%= link_to "投稿する", new_problem_path, class: "side-header__btn"%>
      </div>
      <div class="side-header__i">
        <i class="fas fa-dog icon"></i>
        <%= link_to "MYページ", user_path(current_user) , class: "side-header__btn "%>
      </div>
      <div class="side-header__i">
        <i class="fas fa-sign-out-alt icon"></i>
        <%= link_to "ログアウト", destroy_user_session_path , data: { confirm: "本当にログアウトします？"},method: :delete, class: "side-header__btn"%>
      </div>
    </div>
  </div>
  <div class="problem-show">
    <div class="problem-show__box">
    <h1 class="page-title">記事詳細</h1>
      <div class="problem-show__container">
        <div class="problem-user">
            <span class="problem-user__post">投稿者</span>
            <%= link_to user_path(@problem.user),class: "problem-user__deco" do%>
              <span class="problem-user__usericon">
                <span class="problem-user__username"><%= @problem.user.username%></span>
                <i class="far fa-arrow-alt-circle-right icon"></i>
              </span>
            <% end %>
          </div>

        <div class="problem-show__card">
          <h3 class="problem-show__classification"><%= @problem.classification%></h3>
          <%= attachment_image_tag @problem, :image ,class: "problem-show__image"%>
          <div class="problem-show__show-box">
            <div class="problem-show__info">
              <span class="problem-show__title-name"><%= @problem.title%></span>
            </div>
            <div class="problem-show__info body">
              <span class="problem-show__title"></span>
              <span class="problem-show__title-body"><%= simple_format @problem.body%></span>
            </div>
          </div>
        </div>
        <%= render partial: 'likes/like' %>
        <div class="problem-show__edit-btn">
          <% if @problem.user.id == current_user.id%>
            <%= link_to '編集する', edit_problem_path(@problem),class: "header__btn add"%>
            <%= link_to '削除する',problem_path(@problem), method: :delete, data: { confirm: "本当に削除しますか？"}, class: "delete-btn"%>
          <% end %>
        </div>
      </div>
    </div>
    <div class="comment-box">
      <% if current_user %>
        <%= form_with(model: [@problem, @comment], local: true, id: "new_comment", class: "comment-box__send") do |f| %>
          <%= f.text_area :content, placeholder: "コメントを書く(任意)",class: "textbox" %>
          <%= f.submit "コメントする" , class: "form__submit"%>
        <% end %>
      <% end %>
      <div class="comments">
        <h4 class="comments__title">＜コメント一覧＞</h4>
        <% if @comments %>
          <% @comments.each do |comment| %>
            <div class="comments__box">
              <p>
                <strong><%= link_to comment.user.username, "/users/#{comment.user_id}" ,class: "comments__username"%></strong>
              </p>
              投稿日: <%= comment.updated_at.strftime("%Y-%m-%d")%>
              <p class="comments__text"><%= comment.content %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= j(render("users/unfollow")) %>");
$("#relationship").html("<%= j(render("users/relationship")) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= j(render("users/follow")) %>");
$("#relationship").html("<%= j(render("users/relationship")) %>");

app/views/users/_follow.html.erb
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォローする", class: "follow-box__btn-follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if user_signed_in? && @user != current_user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_relationship.html.erb
<div class="follower">
  <%= link_to followers_user_path(@user.id), class: "follow-box__links" do %>
    <span class="follow-box__follow-count">フォロワー<%= @user.followers.count %></span>
  <% end %>
</div>
<div class="follow">
  <%= link_to following_user_path(@user.id), class: "follow-box__links" do %>
    <span class="follow-box__follow-count">フォロー<%= @user.following.count %></span>
  <% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "follow-box__btn-release"%>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any?%>
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
  <ul>
    <% @user.errors.full_messages.each do |message|%>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<section class="new">
  <div class="side-header">
    <div class="side-header__top">
      <%= link_to problems_path, class: "header__top-text"  do %>
        <span class="header__animals">Animals</span>
        <span class="header__domi">Domi</span>
      <% end %>
      <div class="side-header__i">
        <i class="fab fa-themeisle icon"></i>
        <%= link_to "トップへ戻る", problems_path , class: "side-header__btn"%>
      </div>
      <div class="side-header__i">
        <i class="fas fa-cannabis icon"></i>
        <%= link_to "投稿する", new_problem_path, class: "side-header__btn"%>
      </div>
      <div class="side-header__i">
        <i class="fas fa-dog icon"></i>
        <%= link_to "MYページ", user_path(current_user) , class: "side-header__btn "%>
      </div>
      <div class="side-header__i">
        <i class="fas fa-sign-out-alt icon"></i>
        <%= link_to "ログアウト", destroy_user_session_path , data: { confirm: "本当にログアウトします？"},method: :delete, class: "side-header__btn"%>
      </div>
    </div>
  </div>


  <div class="message">
    <h1  class="page-title">ユーザー編集</h1>
      <div class="message__container">
        <%= form_with model: @user do |f| %>
        <div class="message__box">
          <div class="field">
            <%# <i class="fas fa fa-user"></i> %>
            <%= f.label :username, 'お名前', class: "field__name" %><br />
            <%= f.text_field :username, class: "field__post"%>
          </div>

          <div class="field">
            <%# <i class="fas fa fa-envelope"></i> %>
            <%= f.label :email,'メールアドレス' , class: "field__name"%><br />
            <%= f.email_field :email, class: "field__post"%>
          </div>

          <div class="field">
            <%# <i class="fas fa fa-id-card"></i> %>
            <%= f.label :profile , "プロフィール", class: "field__name"%><br />
            <%= f.text_area :profile, class: "field__body" %>
          </div>

          <div class="field">
            <div id="image-preview">
              <%= f.label :profile_image , "プロフィール画像", class: "field__name"%><br />
              <%= attachment_image_tag @user, :profile_image, class: "img-square", fallback: "no-image.png", size:"150x150" ,style: "border-radius: 50%"%>
            </div>
              <%= f.attachment_field :profile_image , id: "preview", class: "field__image-box"%>
          </div>

          <div class="actions">
            <%= f.submit "更新", class: "side-header__btn" %>
          </div>
        </div>
        <% end %>
     </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="new">
  <div class="side-header">
    <div class="side-header__top">
      <%= link_to problems_path, class: "header__top-text"  do %>
        <span class="header__animals">Animals</span>
        <span class="header__domi">Domi</span>
      <% end %>
      <div class="side-header__i">
        <i class="fab fa-themeisle icon"></i>
        <%= link_to "トップへ戻る", problems_path , class: "side-header__btn"%>
      </div>
      <div class="side-header__i">
        <i class="fas fa-cannabis icon"></i>
        <%= link_to "投稿する", new_problem_path, class: "side-header__btn"%>
      </div>
      <div class="side-header__i">
        <i class="fas fa-users icon"></i>
        <%= link_to 'ユーザー一覧', users_path, class: "side-header__btn"%>
      </div>
      <div class="side-header__i">
        <i class="fas fa-sign-out-alt icon"></i>
        <%= link_to "ログアウト", destroy_user_session_path , data: { confirm: "本当にログアウトします？"},method: :delete, class: "side-header__btn"%>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="mypage">
    <h1 class="page-title">マイページ</h1>
      <div class="mypage__box">
        <div class="mypage__user">
          <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png",class: "mypage__image" %>
          <div class="mypage__username">
            <%= @user.username%>
          </div>
          <div class="mypage__edit">
            <% if @user.id == current_user.id%>
              <%= link_to '編集ページへ', edit_user_path(@user),class: "header__btn" %>
            <% end %>
          </div>
          <p class="count">投稿数:<%= @user.problems.count%></p>
          <div id="relationship" class="follow-box">
            <%= render "relationship" %>
            <div>
              <%= render "follow_form" %>
            </div>
          </div>
        </div>
        <div class="mypage__profile-box">
          <h3 class="mypage__title-info">紹介文</h3>
          <%= @user.profile%>
        </div>
      </div>
    </div>

    <div class="post-show">
      <% @user.problems.each do |problem|%>
        <div class="post-show__box">
          <%= link_to problem_path(problem),class: "post-show__link" do%>
            <%= attachment_image_tag problem, :image ,class: "post-show__image"%>
            <p class="post-show__title"><%= problem.title%></p>
          <%end%>
          <% if @user.id == current_user.id%>
            <%= link_to edit_problem_path(problem), class: "edit-delete" do %>
              <span class="edit-btn">編集</span>
            <% end %>
            <%= link_to problem_path(problem), method: :delete, data: { confirm: "本当に削除しますか？"}, class: "edit-delete" do%>
               <span class="delete-btn">削除</span>
            <% end %>
          <% end %>
          <p class="data">投稿日：<%= problem.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
        </div>
      <% end %>
    </div>
  </div>
</section>